on:
  push:
    branches:
      - master
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish NuGet package
    env:
      BUILD_DIRECTORY: "./artifacts/"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET Core @ Latest
        uses: actions/setup-dotnet@v1.8.1
        with:
          dotnet-version: 5.0.x
          include-prerelease: true

      - name: Build solution and generate NuGet package
        run: |
          cd <project>
          dotnet pack -c Release -o ${{ env.ARTIFACTS_DIRECTORY }}

      - name: Push generated package to GitHub registry
        run: dotnet nuget push ${{ env.ARTIFACTS_DIRECTORY }}*.nupkg\
          --api-key ${{ secrets.NUGET_API_KEY }}\
          --source https://api.nuget.org/v3/index.json\
          --skip-duplicate --no-symbols true
