on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish NuGet package
    env:
      BUILD_DIRECTORY: "./artifacts/"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET Core @ Latest
        uses: actions/setup-dotnet@v1.9.0
        with:
          dotnet-version: 5.0.x

      - name: Build solution and generate NuGet package
        run: dotnet pack OptiTemplates.csproj -c Release -o ${{ env.ARTIFACTS_DIRECTORY }}

      - name: Add GH repo
        run: dotnet nuget add source --username USERNAME --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/dqhoang/index.json"

      - name: Push generated package to GitHub registry
        run: dotnet nuget push ${{ env.ARTIFACTS_DIRECTORY }}*.nupkg --source "github" --skip-duplicate --no-symbols true
